-- schema_v75_permissions_engine.sql
-- Phase A of the Admin-Configurable Permissions Engine
-- (see Documents/Internal/RBAC_Permissions_Engine_Scoping.docx v1.1, Section 10 & 11).
--
-- Creates three new tables (roles, capabilities, role_permissions) and seeds
-- them to reflect the DECIDED target state from the scoping doc's Decisions Log
-- (Section 11) -- not a literal snapshot of today's behaviour, per Decision 4's
-- ASAP framing. The five resolved findings (Section 11.2) are baked into this
-- seed directly rather than deferred to a later cleanup phase.
--
-- Additive only: no existing table (users, user_companies, etc.) is touched.
-- user_companies.role stays a free-text column for now; converting it to a real
-- FK into roles(id) is deferred to Phase C, when server.js actually starts
-- consulting role_permissions via the can() primitive -- doing that conversion
-- now would be a schema change with no consumer yet, on a live table, for no
-- benefit. Nothing in this migration changes what any user can currently do.
--
-- Idempotent: safe to re-run. Uses IF NOT EXISTS / ON CONFLICT throughout.

-- ── 1. roles ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE,
        -- NULL = built-in role, shared across all companies.
    name VARCHAR(100) NOT NULL,
    is_builtin BOOLEAN NOT NULL DEFAULT false,
        -- true for the 8 roles seeded below; protects them from deletion in the
        -- future admin UI (Phase B).
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Built-in role names are globally unique; a future company's custom role name
-- only needs to be unique within that company.
CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_builtin_name
    ON roles (name) WHERE company_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_company_name
    ON roles (company_id, name) WHERE company_id IS NOT NULL;

-- ── 2. capabilities ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS capabilities (
    key VARCHAR(100) PRIMARY KEY,
    module VARCHAR(100) NOT NULL,
    label VARCHAR(200) NOT NULL,
    supports_scope BOOLEAN NOT NULL DEFAULT false,
        -- true if None/Own/Dept/Full applies; false if the capability is a plain
        -- on/off (role_permissions.scope will only ever be 'none' or 'full').
    is_baseline BOOLEAN NOT NULL DEFAULT false,
        -- Decision 3: true means this capability is hardcoded always-true in the
        -- future can() primitive (Phase C) and deliberately has NO rows in
        -- role_permissions -- granted to every role, present and future, and not
        -- editable from the Roles & Permissions admin screen (Phase B).
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── 3. role_permissions ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    capability_key VARCHAR(100) NOT NULL REFERENCES capabilities(key) ON DELETE CASCADE,
    scope VARCHAR(10) NOT NULL DEFAULT 'none' CHECK (scope IN ('none','own','dept','full')),
    updated_by INT REFERENCES users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, capability_key)
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions (role_id);

-- ── 4. Seed the 8 built-in roles ───────────────────────────────────────────
-- Matches user_companies_role_check exactly (schema_v68_super_admin.sql).
-- Deliberately NOT seeding 'Approver': confirmed dead code (Finding 4) -- the
-- role was renamed to 'Risk Owner' in schema_v54_rename_roles.sql, but one
-- backend route (server.js:8618/8669/8704, risk-appetite view) still lists the
-- old string alongside the already-present 'Risk Owner', making it fully
-- redundant. No user can hold it; it is not part of the target role model.
INSERT INTO roles (company_id, name, is_builtin) VALUES
    (NULL, 'Admin', true),
    (NULL, 'Super Admin', true),
    (NULL, 'Risk Manager', true),
    (NULL, 'Risk Champion', true),
    (NULL, 'Risk Owner', true),
    (NULL, 'CRO', true),
    (NULL, 'Consultant CRO', true),
    (NULL, 'Viewer', true)
ON CONFLICT DO NOTHING;

-- ── 5. Seed capabilities ────────────────────────────────────────────────────
INSERT INTO capabilities (key, module, label, supports_scope, is_baseline) VALUES
    ('risk.view', 'Risk Register', 'View risks', true, false),
    ('risk.create', 'Risk Register', 'Create a risk', false, false),
    ('risk.edit', 'Risk Register', 'Edit a risk', true, false),
    ('risk.approve_manager', 'Risk Register', 'Manager-level risk approval', false, false),
    ('risk.approve_first_line', 'Risk Register', 'First-line risk approval (Approver step)', false, false),
    ('risk.reject', 'Risk Register', 'Reject/send back a risk', false, false),
    ('risk.close', 'Risk Register', 'Close a risk', false, false),
    ('risk.reopen', 'Risk Register', 'Reopen a risk', false, false),
    ('risk.cro_accept', 'Risk Register', 'CRO risk acceptance', false, false),
    ('risk.cro_decline', 'Risk Register', 'CRO decline / send back', false, false),
    ('risk.link_related', 'Risk Register', 'Link related risks', false, false),
    ('risk.mitigation.manage', 'Risk Register', 'Manage mitigation action plan items', true, false),
    ('risk.auto_approve', 'Risk Register', 'Auto-approve own submitted risks', false, false),
    ('control.view', 'Control Library', 'View controls', true, false),
    ('control.create', 'Control Library', 'Create/edit controls', false, false),
    ('control.edit', 'Control Library', 'Edit controls', false, false),
    ('control.link_to_risk', 'Control Library', 'Link control to risk', false, false),
    ('control.test', 'Control Library', 'Record a control test result', false, false),
    ('control.test_history.view', 'Control Library', 'View control test history', true, false),
    ('kri.view', 'KRI Library & Register', 'View KRIs', true, false),
    ('kri.manage_definition', 'KRI Library & Register', 'Define/edit a KRI', false, false),
    ('kri.record_measurement', 'KRI Library & Register', 'Record a KRI measurement', false, false),
    ('org_roles.view', 'Org Roles (RACI)', 'View org roles / RACI', false, false),
    ('org_roles.manage', 'Org Roles (RACI)', 'Manage org roles directory', false, false),
    ('raci.view', 'Org Roles (RACI)', 'View RACI matrix', false, false),
    ('raci.edit', 'Org Roles (RACI)', 'Edit RACI matrix', false, false),
    ('policy.view', 'Policy Repository', 'View policies', false, false),
    ('policy.create', 'Policy Repository', 'Create a policy', false, false),
    ('policy.edit', 'Policy Repository', 'Edit a policy / new version', false, false),
    ('policy.transition', 'Policy Repository', 'Transition policy status', false, false),
    ('policy.attest', 'Policy Repository', 'Attest to a policy', false, false),
    ('policy.manage_confidential_access', 'Policy Repository', 'Manage confidential policy access list', false, false),
    ('obligation.view', 'Compliance Obligations & Calendar', 'View obligations', true, false),
    ('obligation.manage', 'Compliance Obligations & Calendar', 'Manage obligations', false, false),
    ('obligation.view_history', 'Compliance Obligations & Calendar', 'View obligation history', false, false),
    ('calendar.view', 'Compliance Obligations & Calendar', 'View compliance calendar', true, false),
    ('issue.view', 'Issues & Actions', 'View issues', true, false),
    ('issue.create', 'Issues & Actions', 'Create an issue', true, false),
    ('issue.edit', 'Issues & Actions', 'Edit an issue', true, false),
    ('issue.update_status', 'Issues & Actions', 'Update issue status', true, false),
    ('issue.action.manage', 'Issues & Actions', 'Manage issue action items', true, false),
    ('incident.view', 'Incident Log', 'View incidents', true, false),
    ('incident.edit', 'Incident Log', 'Edit an incident', true, false),
    ('incident.delete', 'Incident Log', 'Delete an incident', false, false),
    ('incident.link_risk', 'Incident Log', 'Link incident to a risk', true, false),
    ('incident.dismiss', 'Incident Log', 'Dismiss an incident', true, false),
    ('evidence.view', 'Evidence', 'View / download evidence', true, false),
    ('evidence.upload', 'Evidence', 'Upload evidence', true, false),
    ('evidence.delete', 'Evidence', 'Delete evidence', false, false),
    ('evidence.bulk_manage', 'Evidence', 'Bulk evidence admin tools', false, false),
    ('dashboard.management_summary.view', 'Dashboards & Tasks', 'View management summary dashboard', false, false),
    ('tasks.my_tasks.view', 'Dashboards & Tasks', 'View My Tasks (identity-scoped, always self)', true, false),
    ('risk_appetite.view', 'Risk Appetite & Scoring', 'View risk appetite statements', false, false),
    ('risk_appetite.manage', 'Risk Appetite & Scoring', 'Manage risk appetite statements', false, false),
    ('scoring_methodology.view', 'Risk Appetite & Scoring', 'View scoring methodology', false, false),
    ('scoring_methodology.manage', 'Risk Appetite & Scoring', 'Manage scoring methodology', false, false),
    ('data.import', 'Import / Export / Search', 'Import data', false, false),
    ('data.export', 'Import / Export / Search', 'Export data', false, false),
    ('data.seed_controls', 'Import / Export / Search', 'Seed reference controls', false, false),
    ('search.global', 'Import / Export / Search', 'Global search', true, false),
    ('horizon.view', 'Horizon Scanning', 'View horizon scans', false, false),
    ('horizon.manage', 'Horizon Scanning', 'Create/edit/convert horizon scans', false, false),
    ('horizon.delete', 'Horizon Scanning', 'Delete a horizon scan', false, false),
    ('horizon.ai_draft', 'Horizon Scanning', 'Generate AI draft scan', false, false),
    ('risk_gov_docs.view', 'Risk Gov. Documents & Forms', 'View risk governance documents', false, false),
    ('risk_gov_docs.manage', 'Risk Gov. Documents & Forms', 'Manage risk governance documents', false, false),
    ('forms.accepted_risk_report', 'Risk Gov. Documents & Forms', 'Accepted-risk report / Management Pack', false, false),
    ('users.manage', 'Users & Company Admin', 'Manage users', false, false),
    ('roles.manage', 'Users & Company Admin', 'Manage roles & permissions (this engine’s own admin screen)', false, false),
    ('departments.manage', 'Users & Company Admin', 'Manage departments', false, false),
    ('business_units.manage', 'Users & Company Admin', 'Manage business units', false, false),
    ('company.manage', 'Users & Company Admin', 'Manage company profile', false, false),
    ('branding.manage', 'Users & Company Admin', 'Manage branding', false, false),
    ('email_settings.manage', 'Users & Company Admin', 'Manage email settings', false, false),
    ('ai_settings.manage', 'Users & Company Admin', 'Manage AI integration settings', false, false),
    ('storage.manage', 'Users & Company Admin', 'Manage storage & health tools', false, false),
    ('escalation_rules.manage', 'Users & Company Admin', 'Manage escalation rules', false, false),
    ('risk_config.manage', 'Users & Company Admin', 'Manage risk configuration/taxonomy', false, false),
    ('glossary.manage', 'Users & Company Admin', 'Manage glossary', false, false),
    ('audit_log.view', 'Audit', 'View audit log (safety baseline — see Decision 3)', false, true),
    ('incident.create', 'Incident Log', 'Create an incident report (safety baseline — see Decision 3)', false, true)
ON CONFLICT (key) DO UPDATE SET
    module = EXCLUDED.module, label = EXCLUDED.label,
    supports_scope = EXCLUDED.supports_scope, is_baseline = EXCLUDED.is_baseline;

-- ── 6. Seed role_permissions ────────────────────────────────────────────────
-- Baseline capabilities (audit_log.view, incident.create) are deliberately
-- NOT inserted here at all -- see the is_baseline note on the capabilities
-- table above. Every other cell below reflects the decided target state.
INSERT INTO role_permissions (role_id, capability_key, scope)
SELECT r.id, v.capability_key, v.scope
FROM (VALUES
    ('Admin', 'risk.view', 'full'),
    ('Super Admin', 'risk.view', 'full'),
    ('Risk Manager', 'risk.view', 'dept'),
    ('Risk Champion', 'risk.view', 'dept'),
    ('Risk Owner', 'risk.view', 'dept'),
    ('CRO', 'risk.view', 'full'),
    ('Consultant CRO', 'risk.view', 'full'),
    ('Viewer', 'risk.view', 'full'),
    ('Admin', 'risk.create', 'full'),
    ('Super Admin', 'risk.create', 'full'),
    ('Risk Manager', 'risk.create', 'full'),
    ('Risk Champion', 'risk.create', 'full'),
    ('Risk Owner', 'risk.create', 'full'),
    ('CRO', 'risk.create', 'full'),
    ('Consultant CRO', 'risk.create', 'full'),
    ('Admin', 'risk.edit', 'full'),
    ('Super Admin', 'risk.edit', 'full'),
    ('Risk Manager', 'risk.edit', 'dept'),
    ('Risk Champion', 'risk.edit', 'own'),
    ('Risk Owner', 'risk.edit', 'dept'),
    ('CRO', 'risk.edit', 'full'),
    ('Consultant CRO', 'risk.edit', 'full'),
    ('Admin', 'risk.approve_manager', 'full'),
    ('Super Admin', 'risk.approve_manager', 'full'),
    ('Risk Manager', 'risk.approve_manager', 'full'),
    ('CRO', 'risk.approve_manager', 'full'),
    ('Consultant CRO', 'risk.approve_manager', 'full'),
    ('Admin', 'risk.approve_first_line', 'full'),
    ('Super Admin', 'risk.approve_first_line', 'full'),
    ('Risk Owner', 'risk.approve_first_line', 'full'),
    ('Admin', 'risk.reject', 'full'),
    ('Super Admin', 'risk.reject', 'full'),
    ('Risk Manager', 'risk.reject', 'full'),
    ('CRO', 'risk.reject', 'full'),
    ('Consultant CRO', 'risk.reject', 'full'),
    ('Admin', 'risk.close', 'full'),
    ('Super Admin', 'risk.close', 'full'),
    ('Risk Manager', 'risk.close', 'full'),
    ('CRO', 'risk.close', 'full'),
    ('Consultant CRO', 'risk.close', 'full'),
    ('Admin', 'risk.reopen', 'full'),
    ('Super Admin', 'risk.reopen', 'full'),
    ('Risk Manager', 'risk.reopen', 'full'),
    ('CRO', 'risk.reopen', 'full'),
    ('Consultant CRO', 'risk.reopen', 'full'),
    ('Admin', 'risk.cro_accept', 'full'),
    ('Super Admin', 'risk.cro_accept', 'full'),
    ('CRO', 'risk.cro_accept', 'full'),
    ('Consultant CRO', 'risk.cro_accept', 'full'),
    ('Admin', 'risk.cro_decline', 'full'),
    ('Super Admin', 'risk.cro_decline', 'full'),
    ('CRO', 'risk.cro_decline', 'full'),
    ('Consultant CRO', 'risk.cro_decline', 'full'),
    ('Admin', 'risk.link_related', 'full'),
    ('Super Admin', 'risk.link_related', 'full'),
    ('Risk Manager', 'risk.link_related', 'full'),
    ('Risk Champion', 'risk.link_related', 'full'),
    ('CRO', 'risk.link_related', 'full'),
    ('Consultant CRO', 'risk.link_related', 'full'),
    ('Admin', 'risk.mitigation.manage', 'full'),
    ('Super Admin', 'risk.mitigation.manage', 'full'),
    ('Risk Manager', 'risk.mitigation.manage', 'dept'),
    ('Risk Champion', 'risk.mitigation.manage', 'dept'),
    ('Risk Owner', 'risk.mitigation.manage', 'dept'),
    ('CRO', 'risk.mitigation.manage', 'full'),
    ('Consultant CRO', 'risk.mitigation.manage', 'full'),
    ('Super Admin', 'risk.auto_approve', 'full'),
    ('CRO', 'risk.auto_approve', 'full'),
    ('Consultant CRO', 'risk.auto_approve', 'full'),
    ('Admin', 'control.view', 'full'),
    ('Super Admin', 'control.view', 'full'),
    ('Risk Manager', 'control.view', 'dept'),
    ('Risk Champion', 'control.view', 'dept'),
    ('Risk Owner', 'control.view', 'dept'),
    ('CRO', 'control.view', 'full'),
    ('Consultant CRO', 'control.view', 'full'),
    ('Viewer', 'control.view', 'full'),
    ('Admin', 'control.create', 'full'),
    ('Super Admin', 'control.create', 'full'),
    ('Risk Manager', 'control.create', 'full'),
    ('Risk Champion', 'control.create', 'full'),
    ('CRO', 'control.create', 'full'),
    ('Consultant CRO', 'control.create', 'full'),
    ('Admin', 'control.edit', 'full'),
    ('Super Admin', 'control.edit', 'full'),
    ('Risk Manager', 'control.edit', 'full'),
    ('Risk Champion', 'control.edit', 'full'),
    ('CRO', 'control.edit', 'full'),
    ('Consultant CRO', 'control.edit', 'full'),
    ('Admin', 'control.link_to_risk', 'full'),
    ('Super Admin', 'control.link_to_risk', 'full'),
    ('Risk Manager', 'control.link_to_risk', 'full'),
    ('Risk Champion', 'control.link_to_risk', 'full'),
    ('CRO', 'control.link_to_risk', 'full'),
    ('Consultant CRO', 'control.link_to_risk', 'full'),
    ('Admin', 'control.test', 'full'),
    ('Super Admin', 'control.test', 'full'),
    ('Risk Manager', 'control.test', 'full'),
    ('CRO', 'control.test', 'full'),
    ('Consultant CRO', 'control.test', 'full'),
    ('Admin', 'control.test_history.view', 'full'),
    ('Super Admin', 'control.test_history.view', 'full'),
    ('Risk Manager', 'control.test_history.view', 'full'),
    ('Risk Champion', 'control.test_history.view', 'dept'),
    ('Risk Owner', 'control.test_history.view', 'dept'),
    ('CRO', 'control.test_history.view', 'full'),
    ('Consultant CRO', 'control.test_history.view', 'full'),
    ('Viewer', 'control.test_history.view', 'full'),
    ('Admin', 'kri.view', 'full'),
    ('Super Admin', 'kri.view', 'full'),
    ('Risk Manager', 'kri.view', 'dept'),
    ('Risk Champion', 'kri.view', 'dept'),
    ('Risk Owner', 'kri.view', 'dept'),
    ('CRO', 'kri.view', 'full'),
    ('Consultant CRO', 'kri.view', 'full'),
    ('Viewer', 'kri.view', 'full'),
    ('Admin', 'kri.manage_definition', 'full'),
    ('Super Admin', 'kri.manage_definition', 'full'),
    ('Risk Manager', 'kri.manage_definition', 'full'),
    ('CRO', 'kri.manage_definition', 'full'),
    ('Consultant CRO', 'kri.manage_definition', 'full'),
    ('Admin', 'kri.record_measurement', 'full'),
    ('Super Admin', 'kri.record_measurement', 'full'),
    ('Risk Manager', 'kri.record_measurement', 'full'),
    ('CRO', 'kri.record_measurement', 'full'),
    ('Consultant CRO', 'kri.record_measurement', 'full'),
    ('Admin', 'org_roles.view', 'full'),
    ('Super Admin', 'org_roles.view', 'full'),
    ('Risk Manager', 'org_roles.view', 'full'),
    ('Risk Champion', 'org_roles.view', 'full'),
    ('Risk Owner', 'org_roles.view', 'full'),
    ('CRO', 'org_roles.view', 'full'),
    ('Consultant CRO', 'org_roles.view', 'full'),
    ('Viewer', 'org_roles.view', 'full'),
    ('Admin', 'org_roles.manage', 'full'),
    ('Super Admin', 'org_roles.manage', 'full'),
    ('Risk Manager', 'org_roles.manage', 'full'),
    ('CRO', 'org_roles.manage', 'full'),
    ('Consultant CRO', 'org_roles.manage', 'full'),
    ('Admin', 'raci.view', 'full'),
    ('Super Admin', 'raci.view', 'full'),
    ('Risk Manager', 'raci.view', 'full'),
    ('Risk Champion', 'raci.view', 'full'),
    ('Risk Owner', 'raci.view', 'full'),
    ('CRO', 'raci.view', 'full'),
    ('Consultant CRO', 'raci.view', 'full'),
    ('Viewer', 'raci.view', 'full'),
    ('Admin', 'raci.edit', 'full'),
    ('Super Admin', 'raci.edit', 'full'),
    ('CRO', 'raci.edit', 'full'),
    ('Consultant CRO', 'raci.edit', 'full'),
    ('Admin', 'policy.view', 'full'),
    ('Super Admin', 'policy.view', 'full'),
    ('Risk Manager', 'policy.view', 'full'),
    ('Risk Champion', 'policy.view', 'full'),
    ('Risk Owner', 'policy.view', 'full'),
    ('CRO', 'policy.view', 'full'),
    ('Consultant CRO', 'policy.view', 'full'),
    ('Viewer', 'policy.view', 'full'),
    ('Admin', 'policy.create', 'full'),
    ('Super Admin', 'policy.create', 'full'),
    ('Risk Manager', 'policy.create', 'full'),
    ('Risk Champion', 'policy.create', 'full'),
    ('CRO', 'policy.create', 'full'),
    ('Consultant CRO', 'policy.create', 'full'),
    ('Admin', 'policy.edit', 'full'),
    ('Super Admin', 'policy.edit', 'full'),
    ('Risk Manager', 'policy.edit', 'full'),
    ('Risk Champion', 'policy.edit', 'full'),
    ('CRO', 'policy.edit', 'full'),
    ('Consultant CRO', 'policy.edit', 'full'),
    ('Admin', 'policy.transition', 'full'),
    ('Super Admin', 'policy.transition', 'full'),
    ('Risk Manager', 'policy.transition', 'full'),
    ('Risk Champion', 'policy.transition', 'full'),
    ('Risk Owner', 'policy.transition', 'full'),
    ('CRO', 'policy.transition', 'full'),
    ('Consultant CRO', 'policy.transition', 'full'),
    ('Admin', 'policy.attest', 'full'),
    ('Super Admin', 'policy.attest', 'full'),
    ('Risk Manager', 'policy.attest', 'full'),
    ('Risk Champion', 'policy.attest', 'full'),
    ('Risk Owner', 'policy.attest', 'full'),
    ('CRO', 'policy.attest', 'full'),
    ('Consultant CRO', 'policy.attest', 'full'),
    ('Admin', 'policy.manage_confidential_access', 'full'),
    ('Super Admin', 'policy.manage_confidential_access', 'full'),
    ('Admin', 'obligation.view', 'full'),
    ('Super Admin', 'obligation.view', 'full'),
    ('Risk Manager', 'obligation.view', 'dept'),
    ('Risk Champion', 'obligation.view', 'dept'),
    ('Risk Owner', 'obligation.view', 'dept'),
    ('CRO', 'obligation.view', 'full'),
    ('Consultant CRO', 'obligation.view', 'full'),
    ('Viewer', 'obligation.view', 'full'),
    ('Admin', 'obligation.manage', 'full'),
    ('Super Admin', 'obligation.manage', 'full'),
    ('Risk Manager', 'obligation.manage', 'full'),
    ('CRO', 'obligation.manage', 'full'),
    ('Consultant CRO', 'obligation.manage', 'full'),
    ('Admin', 'obligation.view_history', 'full'),
    ('Super Admin', 'obligation.view_history', 'full'),
    ('Risk Manager', 'obligation.view_history', 'full'),
    ('Risk Champion', 'obligation.view_history', 'full'),
    ('CRO', 'obligation.view_history', 'full'),
    ('Consultant CRO', 'obligation.view_history', 'full'),
    ('Admin', 'calendar.view', 'full'),
    ('Super Admin', 'calendar.view', 'full'),
    ('Risk Manager', 'calendar.view', 'dept'),
    ('Risk Champion', 'calendar.view', 'dept'),
    ('Risk Owner', 'calendar.view', 'dept'),
    ('CRO', 'calendar.view', 'full'),
    ('Consultant CRO', 'calendar.view', 'full'),
    ('Viewer', 'calendar.view', 'full'),
    ('Admin', 'issue.view', 'full'),
    ('Super Admin', 'issue.view', 'full'),
    ('Risk Manager', 'issue.view', 'dept'),
    ('Risk Champion', 'issue.view', 'dept'),
    ('Risk Owner', 'issue.view', 'dept'),
    ('CRO', 'issue.view', 'full'),
    ('Consultant CRO', 'issue.view', 'full'),
    ('Viewer', 'issue.view', 'full'),
    ('Admin', 'issue.create', 'full'),
    ('Super Admin', 'issue.create', 'full'),
    ('Risk Manager', 'issue.create', 'dept'),
    ('Risk Champion', 'issue.create', 'dept'),
    ('Risk Owner', 'issue.create', 'dept'),
    ('CRO', 'issue.create', 'full'),
    ('Consultant CRO', 'issue.create', 'full'),
    ('Admin', 'issue.edit', 'full'),
    ('Super Admin', 'issue.edit', 'full'),
    ('Risk Manager', 'issue.edit', 'dept'),
    ('Risk Champion', 'issue.edit', 'dept'),
    ('Risk Owner', 'issue.edit', 'dept'),
    ('CRO', 'issue.edit', 'full'),
    ('Consultant CRO', 'issue.edit', 'full'),
    ('Admin', 'issue.update_status', 'full'),
    ('Super Admin', 'issue.update_status', 'full'),
    ('Risk Manager', 'issue.update_status', 'dept'),
    ('Risk Champion', 'issue.update_status', 'dept'),
    ('Risk Owner', 'issue.update_status', 'dept'),
    ('CRO', 'issue.update_status', 'full'),
    ('Admin', 'issue.action.manage', 'full'),
    ('Super Admin', 'issue.action.manage', 'full'),
    ('Risk Manager', 'issue.action.manage', 'dept'),
    ('Risk Champion', 'issue.action.manage', 'dept'),
    ('Risk Owner', 'issue.action.manage', 'dept'),
    ('CRO', 'issue.action.manage', 'full'),
    ('Admin', 'incident.view', 'full'),
    ('Super Admin', 'incident.view', 'full'),
    ('Risk Manager', 'incident.view', 'dept'),
    ('Risk Champion', 'incident.view', 'dept'),
    ('Risk Owner', 'incident.view', 'dept'),
    ('CRO', 'incident.view', 'full'),
    ('Consultant CRO', 'incident.view', 'full'),
    ('Viewer', 'incident.view', 'full'),
    ('Admin', 'incident.edit', 'full'),
    ('Super Admin', 'incident.edit', 'full'),
    ('Risk Manager', 'incident.edit', 'dept'),
    ('Risk Champion', 'incident.edit', 'dept'),
    ('Risk Owner', 'incident.edit', 'dept'),
    ('CRO', 'incident.edit', 'full'),
    ('Consultant CRO', 'incident.edit', 'full'),
    ('Admin', 'incident.delete', 'full'),
    ('Super Admin', 'incident.delete', 'full'),
    ('Risk Manager', 'incident.delete', 'full'),
    ('CRO', 'incident.delete', 'full'),
    ('Consultant CRO', 'incident.delete', 'full'),
    ('Admin', 'incident.link_risk', 'full'),
    ('Super Admin', 'incident.link_risk', 'full'),
    ('Risk Manager', 'incident.link_risk', 'dept'),
    ('Risk Champion', 'incident.link_risk', 'dept'),
    ('Risk Owner', 'incident.link_risk', 'dept'),
    ('CRO', 'incident.link_risk', 'full'),
    ('Consultant CRO', 'incident.link_risk', 'full'),
    ('Admin', 'incident.dismiss', 'full'),
    ('Super Admin', 'incident.dismiss', 'full'),
    ('Risk Manager', 'incident.dismiss', 'dept'),
    ('Risk Champion', 'incident.dismiss', 'dept'),
    ('Risk Owner', 'incident.dismiss', 'dept'),
    ('CRO', 'incident.dismiss', 'full'),
    ('Consultant CRO', 'incident.dismiss', 'full'),
    ('Admin', 'evidence.view', 'full'),
    ('Super Admin', 'evidence.view', 'full'),
    ('Risk Manager', 'evidence.view', 'dept'),
    ('Risk Champion', 'evidence.view', 'dept'),
    ('Risk Owner', 'evidence.view', 'dept'),
    ('CRO', 'evidence.view', 'full'),
    ('Consultant CRO', 'evidence.view', 'full'),
    ('Viewer', 'evidence.view', 'full'),
    ('Admin', 'evidence.upload', 'full'),
    ('Super Admin', 'evidence.upload', 'full'),
    ('Risk Manager', 'evidence.upload', 'dept'),
    ('Risk Champion', 'evidence.upload', 'dept'),
    ('Risk Owner', 'evidence.upload', 'dept'),
    ('CRO', 'evidence.upload', 'full'),
    ('Consultant CRO', 'evidence.upload', 'full'),
    ('Admin', 'evidence.delete', 'full'),
    ('Super Admin', 'evidence.delete', 'full'),
    ('Admin', 'evidence.bulk_manage', 'full'),
    ('Super Admin', 'evidence.bulk_manage', 'full'),
    ('Admin', 'dashboard.management_summary.view', 'full'),
    ('Super Admin', 'dashboard.management_summary.view', 'full'),
    ('Risk Manager', 'dashboard.management_summary.view', 'full'),
    ('Risk Champion', 'dashboard.management_summary.view', 'full'),
    ('Risk Owner', 'dashboard.management_summary.view', 'full'),
    ('CRO', 'dashboard.management_summary.view', 'full'),
    ('Consultant CRO', 'dashboard.management_summary.view', 'full'),
    ('Viewer', 'dashboard.management_summary.view', 'full'),
    ('Admin', 'tasks.my_tasks.view', 'full'),
    ('Super Admin', 'tasks.my_tasks.view', 'full'),
    ('Risk Manager', 'tasks.my_tasks.view', 'own'),
    ('Risk Champion', 'tasks.my_tasks.view', 'own'),
    ('Risk Owner', 'tasks.my_tasks.view', 'own'),
    ('CRO', 'tasks.my_tasks.view', 'own'),
    ('Consultant CRO', 'tasks.my_tasks.view', 'own'),
    ('Admin', 'risk_appetite.view', 'full'),
    ('Super Admin', 'risk_appetite.view', 'full'),
    ('Risk Manager', 'risk_appetite.view', 'full'),
    ('Risk Champion', 'risk_appetite.view', 'full'),
    ('Risk Owner', 'risk_appetite.view', 'full'),
    ('CRO', 'risk_appetite.view', 'full'),
    ('Consultant CRO', 'risk_appetite.view', 'full'),
    ('Viewer', 'risk_appetite.view', 'full'),
    ('Admin', 'risk_appetite.manage', 'full'),
    ('Super Admin', 'risk_appetite.manage', 'full'),
    ('CRO', 'risk_appetite.manage', 'full'),
    ('Consultant CRO', 'risk_appetite.manage', 'full'),
    ('Admin', 'scoring_methodology.view', 'full'),
    ('Super Admin', 'scoring_methodology.view', 'full'),
    ('Risk Manager', 'scoring_methodology.view', 'full'),
    ('Risk Champion', 'scoring_methodology.view', 'full'),
    ('Risk Owner', 'scoring_methodology.view', 'full'),
    ('CRO', 'scoring_methodology.view', 'full'),
    ('Consultant CRO', 'scoring_methodology.view', 'full'),
    ('Viewer', 'scoring_methodology.view', 'full'),
    ('CRO', 'scoring_methodology.manage', 'full'),
    ('Consultant CRO', 'scoring_methodology.manage', 'full'),
    ('Admin', 'data.import', 'full'),
    ('Super Admin', 'data.import', 'full'),
    ('Risk Manager', 'data.import', 'full'),
    ('Risk Champion', 'data.import', 'full'),
    ('CRO', 'data.import', 'full'),
    ('Consultant CRO', 'data.import', 'full'),
    ('Admin', 'data.export', 'full'),
    ('Super Admin', 'data.export', 'full'),
    ('Risk Manager', 'data.export', 'full'),
    ('Risk Champion', 'data.export', 'full'),
    ('CRO', 'data.export', 'full'),
    ('Consultant CRO', 'data.export', 'full'),
    ('Admin', 'data.seed_controls', 'full'),
    ('Super Admin', 'data.seed_controls', 'full'),
    ('Admin', 'search.global', 'full'),
    ('Super Admin', 'search.global', 'full'),
    ('Risk Manager', 'search.global', 'dept'),
    ('Risk Champion', 'search.global', 'own'),
    ('Risk Owner', 'search.global', 'own'),
    ('CRO', 'search.global', 'full'),
    ('Consultant CRO', 'search.global', 'full'),
    ('Admin', 'horizon.view', 'full'),
    ('Super Admin', 'horizon.view', 'full'),
    ('Risk Manager', 'horizon.view', 'full'),
    ('Risk Champion', 'horizon.view', 'full'),
    ('Risk Owner', 'horizon.view', 'full'),
    ('CRO', 'horizon.view', 'full'),
    ('Consultant CRO', 'horizon.view', 'full'),
    ('Admin', 'horizon.manage', 'full'),
    ('Super Admin', 'horizon.manage', 'full'),
    ('Risk Manager', 'horizon.manage', 'full'),
    ('CRO', 'horizon.manage', 'full'),
    ('Consultant CRO', 'horizon.manage', 'full'),
    ('Admin', 'horizon.delete', 'full'),
    ('Super Admin', 'horizon.delete', 'full'),
    ('CRO', 'horizon.delete', 'full'),
    ('Consultant CRO', 'horizon.delete', 'full'),
    ('Admin', 'horizon.ai_draft', 'full'),
    ('Super Admin', 'horizon.ai_draft', 'full'),
    ('CRO', 'horizon.ai_draft', 'full'),
    ('Consultant CRO', 'horizon.ai_draft', 'full'),
    ('Admin', 'risk_gov_docs.view', 'full'),
    ('Super Admin', 'risk_gov_docs.view', 'full'),
    ('Risk Manager', 'risk_gov_docs.view', 'full'),
    ('CRO', 'risk_gov_docs.view', 'full'),
    ('Consultant CRO', 'risk_gov_docs.view', 'full'),
    ('Admin', 'risk_gov_docs.manage', 'full'),
    ('Super Admin', 'risk_gov_docs.manage', 'full'),
    ('Risk Manager', 'risk_gov_docs.manage', 'full'),
    ('CRO', 'risk_gov_docs.manage', 'full'),
    ('Consultant CRO', 'risk_gov_docs.manage', 'full'),
    ('Admin', 'forms.accepted_risk_report', 'full'),
    ('Super Admin', 'forms.accepted_risk_report', 'full'),
    ('CRO', 'forms.accepted_risk_report', 'full'),
    ('Consultant CRO', 'forms.accepted_risk_report', 'full'),
    ('Admin', 'users.manage', 'full'),
    ('Super Admin', 'users.manage', 'full'),
    ('Admin', 'roles.manage', 'full'),
    ('Super Admin', 'roles.manage', 'full'),
    ('Admin', 'departments.manage', 'full'),
    ('Super Admin', 'departments.manage', 'full'),
    ('Admin', 'business_units.manage', 'full'),
    ('Super Admin', 'business_units.manage', 'full'),
    ('Admin', 'company.manage', 'full'),
    ('Super Admin', 'company.manage', 'full'),
    ('Admin', 'branding.manage', 'full'),
    ('Super Admin', 'branding.manage', 'full'),
    ('Admin', 'email_settings.manage', 'full'),
    ('Super Admin', 'email_settings.manage', 'full'),
    ('Admin', 'ai_settings.manage', 'full'),
    ('Super Admin', 'ai_settings.manage', 'full'),
    ('Admin', 'storage.manage', 'full'),
    ('Super Admin', 'storage.manage', 'full'),
    ('Admin', 'escalation_rules.manage', 'full'),
    ('Super Admin', 'escalation_rules.manage', 'full'),
    ('CRO', 'escalation_rules.manage', 'full'),
    ('Consultant CRO', 'escalation_rules.manage', 'full'),
    ('Admin', 'risk_config.manage', 'full'),
    ('Super Admin', 'risk_config.manage', 'full'),
    ('Admin', 'glossary.manage', 'full'),
    ('Super Admin', 'glossary.manage', 'full')
) AS v(role_name, capability_key, scope)
JOIN roles r ON r.name = v.role_name AND r.company_id IS NULL
ON CONFLICT (role_id, capability_key) DO UPDATE SET
    scope = EXCLUDED.scope, updated_at = now();

-- ── 7. Sanity check (raises a NOTICE, does not fail the migration) ────────
DO $$
DECLARE
    v_roles INT; v_caps INT; v_perms INT;
BEGIN
    SELECT count(*) INTO v_roles FROM roles WHERE company_id IS NULL;
    SELECT count(*) INTO v_caps FROM capabilities;
    SELECT count(*) INTO v_perms FROM role_permissions;
    RAISE NOTICE 'Permissions engine seed: % built-in roles, % capabilities, % role_permission rows', v_roles, v_caps, v_perms;
    IF v_roles <> 8 THEN RAISE WARNING 'Expected 8 built-in roles, found %', v_roles; END IF;
END $$;
