import { useEffect, useState } from 'react';

export default function About() {
    const [version, setVersion] = useState('');

    useEffect(() => {
        fetch('/api/version')
            .then((r) => r.json())
            .then((d) => setVersion(d.version || ''))
            .catch(() => {});
    }, []);

    return (
        <div className="card" style={{ maxWidth: 640, width: '100%' }}>
            <h2 style={{ marginTop: 0 }}>About Qatar Post GRC Workstation</h2>
            {version && (
                <p style={{ color: 'var(--color-text-muted)', fontSize: 13, marginTop: -8 }}>
                    Version {version}
                </p>
            )}

            <p>
                Qatar Post GRC Workstation is a governance, risk, and compliance management platform
                built for Qatar Post's structured, audit-ready approach to GRC. It brings together
                risk registers, control libraries, policy repositories, KRI tracking, and issues
                management in a single platform, deployed in a dedicated environment for Qatar Post.
            </p>

            <h3>Built by Certitude Advisory</h3>
            <p>
                Certitude Advisory is a management consulting firm specializing in governance, risk,
                and compliance. Qatar Post GRC Workstation is developed and maintained by Certitude
                Advisory as a proprietary client delivery tool.
            </p>

            <h3>Support &amp; Feedback</h3>
            <p>
                For support, questions, or to report an issue, contact:{' '}
                <a href="mailto:c.kumar@certitude-advisory.ca">c.kumar@certitude-advisory.ca</a>
            </p>

            <h3>Technology</h3>
            <p>
                Hosted on Qatar Post's own infrastructure and maintained by Qatar Post IT. All data
                remains within Qatar Post's environment and is encrypted in transit and at rest.
            </p>

            <hr style={{ margin: '24px 0', borderColor: 'var(--color-border)' }} />

            <h3 style={{ marginTop: 0 }}>Legal Disclaimer</h3>
            <p style={{ fontSize: 13, color: 'var(--color-text-muted)' }}>
                Qatar Post GRC Workstation is a software tool designed to assist in organizing and documenting
                governance, risk, and compliance activities. It does not constitute legal, regulatory,
                accounting, or professional advice of any kind. Outputs generated by this platform are
                for internal organizational use only and should be reviewed by qualified professionals
                before being relied upon for regulatory submissions, audit responses, or compliance
                certifications. Certitude Advisory makes no warranties, express or implied, regarding
                the completeness, accuracy, or fitness for purpose of any content produced through
                this platform.
            </p>
        </div>
    );
}
